import json
from models.schemas import Operation


def generate_notebook(
        operations: list[dict],
        original_filename: str,
        file_extension: str,
) -> dict:
    """
    Generate a Jupyter notebook (.ipynb) that reproduces the cleaning operations
    that were actually applied in the session.
    """
    cells = []

    # ── Cell 1: Imports ────────────────────────────────────────────────────────
    cells.append(_code_cell(
        "# Data Cleaning Pipeline\n"
        "# Generated by Data Cleaner App\n\n"
        "import pandas as pd\n"
        "import numpy as np\n"
    ))

    # ── Cell 2: Load file ──────────────────────────────────────────────────────
    load_code = _generate_load_code(original_filename, file_extension)
    cells.append(_code_cell(load_code))

    # ── Cell 3: Preview ────────────────────────────────────────────────────────
    cells.append(_code_cell(
        "# Preview the raw data\n"
        "df.head()"
    ))

    # ── One cell per operation ─────────────────────────────────────────────────
    for op_dict in operations:
        op = Operation(**op_dict)
        code = _generate_operation_code(op)
        if code:
            cells.append(_code_cell(code))

    # ── Final cell: Save output ────────────────────────────────────────────────
    save_code = _generate_save_code(original_filename, file_extension)
    cells.append(_code_cell(save_code))

    # ── Final cell: Preview cleaned data ──────────────────────────────────────
    cells.append(_code_cell(
        "# Preview the cleaned data\n"
        "df.head()"
    ))

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0",
            },
        },
        "cells": cells,
    }

    return notebook


# ── Cell builders ──────────────────────────────────────────────────────────────

def _code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


# ── File I/O code generators ───────────────────────────────────────────────────

def _generate_load_code(filename: str, ext: str) -> str:
    if ext == "csv":
        return (
            f"# Load the data\n"
            f"df = pd.read_csv('{filename}')\n"
            f"print(f'Loaded {{len(df)}} rows and {{len(df.columns)}} columns')"
        )
    elif ext in ["xls", "xlsx"]:
        return (
            f"# Load the data\n"
            f"df = pd.read_excel('{filename}')\n"
            f"print(f'Loaded {{len(df)}} rows and {{len(df.columns)}} columns')"
        )
    elif ext == "json":
        return (
            f"# Load the data\n"
            f"df = pd.read_json('{filename}')\n"
            f"print(f'Loaded {{len(df)}} rows and {{len(df.columns)}} columns')"
        )
    return f"df = pd.read_csv('{filename}')"


def _generate_save_code(filename: str, ext: str) -> str:
    base = filename.rsplit(".", 1)[0]
    output_name = f"{base}_cleaned.{ext}"

    if ext == "csv":
        return (
            f"# Save the cleaned file\n"
            f"df.to_csv('{output_name}', index=False)\n"
            f"print('Saved cleaned file to {output_name}')"
        )
    elif ext in ["xls", "xlsx"]:
        return (
            f"# Save the cleaned file\n"
            f"df.to_excel('{output_name}', index=False)\n"
            f"print('Saved cleaned file to {output_name}')"
        )
    elif ext == "json":
        return (
            f"# Save the cleaned file\n"
            f"df.to_json('{output_name}', orient='records', indent=2)\n"
            f"print('Saved cleaned file to {output_name}')"
        )
    return f"df.to_csv('{output_name}', index=False)"


# ── Operation code generators ──────────────────────────────────────────────────

def _generate_operation_code(op: Operation) -> str | None:
    generators = {
        "fill_nulls": _code_fill_nulls,
        "remove_duplicates": _code_remove_duplicates,
        "convert_to_datetime": _code_convert_to_datetime,
        "convert_to_numeric": _code_convert_to_numeric,
        "standardize_case": _code_standardize_case,
        "strip_whitespace": _code_strip_whitespace,
        "replace_pseudo_nulls": _code_replace_pseudo_nulls,
        "drop_column": _code_drop_column,
        "drop_rows_where_null": _code_drop_rows_where_null,
        "rename_column": _code_rename_column,
        "cap_outliers": _code_cap_outliers,
        "convert_excel_dates": _code_convert_excel_dates,
        "custom_code": _code_custom_code,
    }
    generator = generators.get(op.operation)
    return generator(op) if generator else None


def _code_fill_nulls(op: Operation) -> str:
    strategy = op.strategy or "median"
    col = op.column or "all"

    if col == "all":
        cols_expr = "df.select_dtypes(include='number').columns"
        comment = f"# Fill null values with {strategy} for all numeric columns"
    else:
        cols_expr = f"['{col}']"
        comment = f"# Fill null values in '{col}' with {strategy}"

    if strategy == "median":
        return f"{comment}\nfor col in {cols_expr}:\n    df[col] = df[col].fillna(df[col].median())"
    elif strategy == "mean":
        return f"{comment}\nfor col in {cols_expr}:\n    df[col] = df[col].fillna(df[col].mean())"
    elif strategy == "mode":
        return f"{comment}\nfor col in {cols_expr}:\n    df[col] = df[col].fillna(df[col].mode()[0])"
    elif strategy == "drop":
        if col == "all":
            return "# Drop rows with any null values\ndf = df.dropna()\nprint(f'Rows after dropping nulls: {len(df)}')"
        return f"# Drop rows where '{col}' is null\ndf = df.dropna(subset=['{col}'])\nprint(f'Rows after dropping nulls: {{len(df)}}')"
    elif op.value is not None:
        return f"{comment}\ndf['{col}'] = df['{col}'].fillna({repr(op.value)})"
    return ""


def _code_remove_duplicates(op: Operation) -> str:
    # Bug fix: was a plain string, not an f-string, so {before - len(df)} printed literally.
    return (
        "# Remove exact duplicate rows\n"
        "before = len(df)\n"
        "df = df.drop_duplicates()\n"
        "print(f'Removed {before - len(df)} duplicate rows')"
    )


def _code_convert_to_datetime(op: Operation) -> str:
    col = op.column
    fmt = op.format

    # Bug fix: the original used a fragile .replace("{col}", ...) hack which would
    # corrupt output if the column name happened to contain the literal text "{col}".
    # Build the string directly with proper quoting instead.
    if fmt:
        parse_expr = f"pd.to_datetime(df['{col}'], format='{fmt}', errors='coerce')"
    else:
        parse_expr = f"pd.to_datetime(df['{col}'], errors='coerce')"

    return (
        f"# Convert '{col}' to datetime\n"
        f"df['{col}'] = {parse_expr}\n"
        f"failed = df['{col}'].isna().sum()\n"
        f"print(f'Converted \\'{col}\\' to datetime. {{failed}} values could not be parsed.')"
    )


def _code_convert_to_numeric(op: Operation) -> str:
    col = op.column
    return (
        f"# Convert '{col}' to numeric\n"
        f"df['{col}'] = pd.to_numeric(df['{col}'], errors='coerce')\n"
        f"print(f'Converted \\'{col}\\' to numeric')"
    )


def _code_standardize_case(op: Operation) -> str:
    col = op.column or "all"
    to = op.to or "lower"
    method = {"lower": "str.lower()", "upper": "str.upper()", "title": "str.title()"}.get(to, "str.lower()")

    if col == "all":
        return (
            f"# Standardize text casing to {to} for all string columns\n"
            f"for col in df.select_dtypes(include='object').columns:\n"
            f"    df[col] = df[col].{method}"
        )
    return f"# Standardize casing in '{col}' to {to}\ndf['{col}'] = df['{col}'].{method}"


def _code_strip_whitespace(op: Operation) -> str:
    col = op.column or "all"

    if col == "all":
        return (
            "# Strip leading/trailing whitespace from all string columns\n"
            "for col in df.select_dtypes(include='object').columns:\n"
            "    df[col] = df[col].str.strip()"
        )
    return f"# Strip whitespace from '{col}'\ndf['{col}'] = df['{col}'].str.strip()"


def _code_replace_pseudo_nulls(op: Operation) -> str:
    col = op.column or "all"
    pseudo = ["N/A", "n/a", "NA", "na", "none", "None", "NULL", "null", "-", "?", ""]

    if col == "all":
        return (
            f"# Replace pseudo-null values with actual NaN\n"
            f"pseudo_nulls = {pseudo}\n"
            f"for col in df.select_dtypes(include='object').columns:\n"
            f"    df[col] = df[col].replace(pseudo_nulls, np.nan)"
        )
    return (
        f"# Replace pseudo-null values in '{col}' with actual NaN\n"
        f"pseudo_nulls = {pseudo}\n"
        f"df['{col}'] = df['{col}'].replace(pseudo_nulls, np.nan)"
    )


def _code_drop_column(op: Operation) -> str:
    return (
        f"# Drop column '{op.column}'\n"
        f"df = df.drop(columns=['{op.column}'])"
    )


def _code_drop_rows_where_null(op: Operation) -> str:
    col = op.column or "all"
    if col == "all":
        return (
            "# Drop rows with any null values\n"
            "before = len(df)\n"
            "df = df.dropna()\n"
            "print(f'Dropped {before - len(df)} rows')"
        )
    return (
        f"# Drop rows where '{col}' is null\n"
        f"before = len(df)\n"
        f"df = df.dropna(subset=['{col}'])\n"
        f"print(f'Dropped {{before - len(df)}} rows where \\'{col}\\' was null')"
    )


def _code_rename_column(op: Operation) -> str:
    return (
        f"# Rename column '{op.column}' to '{op.value}'\n"
        f"df = df.rename(columns={{'{op.column}': '{op.value}'}})"
    )


def _code_cap_outliers(op: Operation) -> str:
    col = op.column or "all"

    cap_block = (
        "    Q1 = df[col].quantile(0.25)\n"
        "    Q3 = df[col].quantile(0.75)\n"
        "    IQR = Q3 - Q1\n"
        "    lower = Q1 - 1.5 * IQR\n"
        "    upper = Q3 + 1.5 * IQR\n"
        "    df[col] = df[col].clip(lower=lower, upper=upper)"
    )

    if col == "all":
        return (
                "# Cap outliers using IQR method for all numeric columns\n"
                "for col in df.select_dtypes(include='number').columns:\n"
                + cap_block
        )
    return (
            f"# Cap outliers in '{col}' using IQR method\n"
            f"col = '{col}'\n"
            + cap_block.replace("    ", "")
    )


def _code_convert_excel_dates(op: Operation) -> str:
    col = op.column
    return (
        f"# Convert Excel date serial numbers in '{col}' to datetime\n"
        f"df['{col}'] = pd.TimedeltaIndex(df['{col}'], unit='d') + pd.Timestamp('1899-12-30')"
    )


def _code_custom_code(op: Operation) -> str:
    code = op.code or ""
    description = op.description or "Custom operation"
    return (
        f"# {description}\n"
        f"{code}"
    )